---
# Copyright 2018 SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-helm-lint
        - openstack-helm-infra-aio-logging
        - openstack-helm-infra-aio-monitoring
        - openstack-helm-infra-aio-network-policy:
            voting: false
        - openstack-helm-infra-openstack-support
        - openstack-helm-infra-kubernetes-keystone-auth
        # some testing performed here to check for any break of host/label
        # override functionality
        - openstack-helm-infra-airship-divingbell:
            voting: false
        - openstack-helm-infra-aio-podsecuritypolicy:
            voting: false
        - openstack-helm-infra-apparmor:
            voting: false
    gate:
      jobs:
        - openstack-helm-lint
        - openstack-helm-infra-aio-logging
        - openstack-helm-infra-aio-monitoring
        - openstack-helm-infra-openstack-support
        - openstack-helm-infra-kubernetes-keystone-auth
    periodic:
      jobs:
        - openstack-helm-infra-tenant-ceph
        - openstack-helm-infra-five-ubuntu
        - openstack-helm-infra-armada-deploy
        - openstack-helm-infra-armada-update-uuid
        - openstack-helm-infra-armada-update-passwords
    experimental:
      jobs:
        # NOTE(srwilkers): Disable fedora experimental jobs until issues resolved
        #- openstack-helm-infra-five-fedora
        # NOTE(srwilkers): Disable centos experimental jobs until issues resolved
        #- openstack-helm-infra-five-centos
        - openstack-helm-infra-tenant-ceph
        - openstack-helm-infra-elastic-beats
        - openstack-helm-infra-armada-deploy
        - openstack-helm-infra-armada-update-uuid
        - openstack-helm-infra-armada-update-passwords