# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: installing community ceph repository
  when: kubelet.pv_support_ceph
  block:
  - name: ubuntu | ensure community ceph repository key is installed
    when: ansible_distribution == "Ubuntu"
    shell: wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -

  - name: ubuntu | ensure community ceph repository exists
    when: ansible_distribution == 'Ubuntu'
    apt_repository:
      repo: "deb https://download.ceph.com/debian-mimic/ {{ ansible_lsb.codename }} main"
      state: present
      update_cache: yes

  - name: centos | ensure community ceph repository exists
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    yum_repository:
      name: ceph
      description: "Ceph community packages for Redhat/Centos"
      gpgkey: "https://download.ceph.com/keys/release.asc"
      baseurl: "https://download.ceph.com/rpm-mimic/el7/$basearch"
      gpgcheck: yes
      state: present

- name: centos | installing epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - epel-release

- name: centos | installing SElinux support packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - libselinux-python

- name: fedora | installing SElinux support packages
  when: ansible_distribution == 'Fedora'
  dnf:
    name: "{{item}}"
    state: installed
  with_items:
    - libselinux-python

- name: installing ceph support packages
  when: kubelet.pv_support_ceph
  block:
  - name: ubuntu | installing packages
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    apt:
      name: "{{item}}"
      state: latest
    with_items:
        - ceph-common
        - rbd-nbd

  - name: ubuntu | uninstall packages
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    apt:
      name: "{{item}}"
      state: absent
    with_items:
        - ceph

  - name: centos | installing packages
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    yum:
      name: "{{item}}"
      state: latest
    with_items:
        - ceph-common
        - rbd-nbd

  - name: centos | installing packages
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    yum:
      name: "{{item}}"
      state: absent
    with_items:
        - ceph

- name: blacklist kernel RBD driver module
  when: kubelet.pv_support_ceph
  copy:
    dest: "/etc/modprobe.d/rbd.conf"
    content: "install rbd /bin/true"

- when: kubelet.pv_support_nfs
  name: installing NFS support packages
  include_role:
    name: deploy-package
    tasks_from: dist
  vars:
    packages:
      deb:
        - nfs-common
      rpm:
        - nfs-utils

- name: installing LinuxBridge support
  when: kubelet.net_support_linuxbridge
  include_role:
    name: deploy-package
    tasks_from: dist
  vars:
    packages:
      deb:
        - bridge-utils
      rpm:
        - bridge-utils
